CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
cardSerialNumber TEXT NOT NULL,
email TEXT NOT NULL,
note TEXT
);

CREATE TABLE IF NOT EXISTS log (
id INTEGER PRIMARY KEY AUTOINCREMENT,
timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
cardSerialNumber TEXT NOT NULL,
result TEXT,
note TEXT
);
