[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"
serde = { version = "1.0.196", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }
